#指定dubbo服务名称
spring:
  application:
    name: dubbo-studentservice
#dubbo配置
dubbo:
  #注册中心
  registry:
    address: zookeeper://localhost:2181
    #使用的协议
  protocol:
    name: dubbo
  #扫描注解
  scan:
    base-packages: com.bjpowernode.service
   #提供者默认值
  provider:
    timeout: 5000
    retries: 0
